const shapeSize = .3
// const shapeSize = [.3, .5, .2].fast(8)
const shapeXRepeat = [3, .5].smooth().fast(.2)
const shapeYRepeat = [.5, 3].smooth().fast(.2)
shapePat = () => shape([3, 5, 4, 5].fast(1), shapeSize, 0.25)
// 	.rotate(() => -Math.sin(time) * 8)
//     .repeat(shapeXRepeat, shapeYRepeat)
//     .rotate(() => Math.sin(time * .5) * 10)
// shapePat().out()
const n = 1/5
shapePat()
    //     .add(shapePat().scrollX(n).scrollY(n))
    //     .modulate(src(o1).add(noise(2), .1), 1) // adds some noise
    //     .add(src(o1).scrollY(-1, -0.2), 1)
    //     .invert()
    .out(o1)

// src(o1).out()

src(o1)
    .colorama(1.2)
    .posterize(4)
    .saturate(0.7)
    .contrast(6)
    .mult(solid(), 0.15)
    .add(o3, .5)
    .out(o2)
// src(o2).out()

osc(0.5, 1.25)
    .mult(shape(1, 0.09)
        .rotate(1.5))
    .diff(gradient())
    //     .add(shape(2, 2)
    //         .blend(gradient(1)))
    //     .colorama(1)
    .modulate(noise()
        .modulate(noise()
            .scrollY(1, 0.0625)))
    //     .blend(o3)
    //     .color(1, -0.5, -0.75)
    .out(o3)
// src(o3).out()

s1.initVideo("http://localhost:8080/video/lav/lav")

src(s1)
    // 	.diff(noise(4, [1, 5].fast(8))
    //   			.add(osc(10, 1, 1), .5).sub(o2, .3)
    //   	,.4)
    // .sub(noise(1, [1, 5].fast(.8)), [.1, .7].smooth())
    // .add(o3, [.2, .8].smooth())
    .add(o2, .5)
    //     .colorama(1.2)
    //     .posterize(4)
    //     .saturate(0.7)
    //     .contrast(6)
    //     .mult(solid(), 0.15)
    //     .add(o3, .5)
    // .rotate(0, .2)
    // 	.repeat(2,3)
    //         .scrollX(.5, .05)
    //         .scrollY(.15, [-.025, .025].smooth().fast(.06))
    //         .kaleid([1, 3].smooth().fast(.01))
    //     	.posterize(1.5)
    //         .invert(.9)
    .out(o0)